#ifdef VENDOR_EDIT
#wen.luo@BSP.Kernel.Stability 2020/03/25 add for oplus kernel system
obj-$(CONFIG_OPLUS_SYSTEM_KERNEL)    += system/
#endif /* VENDOR_EDIT */

#ifdef OPLUS_FEATURE_TP_BASIC
#Qingwen.Liu@RM.BSP.Basic, 2020/11/03, Add for device info
obj-$(CONFIG_OPPO_COMMON_SOFT)  +=  device_info/
#endif /* OPLUS_FEATURE_TP_BASIC */
